name: CI/CD

on:
  push:
    branches: [master]  # or main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t nuha24/web-scraper:latest .

    - name: Run scraper
      run: docker run --rm nuha24/web-scraper:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: docker push nuha24/web-scraper:latest
